### ISSUE TITLE
[Bug] not work in magisk Alpha

### ISSUE THREAD

**Issue by ammlr** [Admirepowered/Zygisk_mod#1]
### Steps to reproduce/复现步骤

1. zygisk magisk off
2.  flash module
3. reboot 
4. warning appears: zygisk not active

### Expected behaviour/预期行为

.
![Screenshot_2024-04-15-02-01-18-860_grzchwtou upqwdwb](https://github.com/Admirepowered/Zygisk_mod/assets/30746607/06990d20-bbac-4dcc-9e07-0e1bc10849bd)

### Actual behaviour/实际行为

.

### KernelSU Module List/KernelSU 模块列表

```Shell
.
```

### Zygisk_mod version/Zygisk_mod 版本

Zygisk_mod-v4-0.9.3-211-6449b1f-release.zip

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

magisk alpha

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk_mod and enable verbose log/我正在使用最新 CI 调试版本 Zygisk_mod 且启用详细日志

### Logs/日志

![Uploading Screenshot_2024-04-15-02-01-18-860_grzchwtou.upqwdwb.jpg…]()

**Comment by Admirepowered** [comment]
i don't see the log,i guess your LSPosed is too old ,is it work in maigsk's zygisk?

**Comment by RinLin-NYA** [comment]
which version of magisk alpha you're using now?
